config_settings = {
    "login_link":"https://www.marketinout.com/home/login.php",
   "test_link":'C:\\Users\\Sonam\\PycharmProjects\\marketBreadth\\StockScreenerResults.html',
    "username":"niteshchawla81@gmail.com",
    "password":"Hotdog@66",
    "match_xpath":"/html/body/table[2]/tbody/tr/td[2]/table[3]/tbody/tr/td/table[1]/tbody/tr[2]/td/table/tbody/tr[25]/td/table/tbody/tr/td[1]/b",

  "match_xpath_crypto":"/html/body/table[2]/tbody/tr/td[2]/table[3]/tbody/tr/td/table[1]/tbody/tr[2]/td/table/tbody/tr[21]/td/table/tbody/tr/td[1]/b",
    "minervini":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=336877",
    "minervini_fn":"_2_USA_MINERVINI_ATH_COMBINED.csv",
    "1_month": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=336862&sorting=cc4&desc=1",
    "1_month_fn": "_14_qullamagie_1_months_USA.csv",
    "3_month": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=336874&sorting=cc5&desc=1",
    "3_month_fn": "_13_quallamagie_3_months_USA.csv",
    "6_month": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=336875&sorting=cc5&desc=1",
    "6_month_fn": "_13_quallamagie_6_months_USA.csv",
    "52_wk_high": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=381839&sorting=cc3&desc=1",
    "52_wk_high_fn": "_usa_52_week_high.csv",
    "usa20percent":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=391273&sorting=cc1&desc=1",
    "usa20percent_fn":"_usa20percent.csv",
    "usa_kma": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=391272",
    "52wbounce": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=395627&sorting=cc1&desc=1",
    "52wbounce_fn":"_usa_bounce_52wlow.csv",
    "usa_kma_fn": "_usa_kma.csv",
    "usa_anticipation_vcp": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=392360&sorting=cc1&desc=1",
    "usa_anticipation_vcp_fn": "_usa_volume_compression_anticipation.csv",
    "usa_refined": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=412741&sorting=cc10&desc=1",
    "usa_refined_fn": "_usa_all_scanner_breakouts_refined.csv",

}