config_settings = {
    "login_link":"https://www.marketinout.com/home/login.php",
   "test_link":'C:\\Users\\Sonam\\PycharmProjects\\marketBreadth\\StockScreenerResults.html',
    "username":"niteshchawla81@gmail.com",
    "password":"Hotdog@66",
    "match_xpath":"/html/body/table[2]/tbody/tr/td[2]/table[3]/tbody/tr/td/table[1]/tbody/tr[2]/td/table/tbody/tr[25]/td/table/tbody/tr/td[1]/b",

  "match_xpath_crypto":"/html/body/table[2]/tbody/tr/td[2]/table[3]/tbody/tr/td/table[1]/tbody/tr[2]/td/table/tbody/tr[21]/td/table/tbody/tr/td[1]/b",
    # "20sma":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=301671&view=ts&mov=0",
    # "50sma": "https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=294862&mov=0",
    # "20sma_below":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=310340&mov=0",
    # "50sma_below":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=310339&mov=0",
    # "20percent_up":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=310341&mov=0",
    # "20percent_down":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=310342&mov=0",
    # "4.5percent_up":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=334513&mov=-102",
    # "4.5percent_down":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=338580&mov=0",
    #"20sma":"https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=301671",
    "20sma":"https://www.marketinout.com/stock-screener/stocks.php?f=1&screen_id=424631&mov=0",
    "50sma": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=294862",
    "20sma_below":"https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=310340",
    "50sma_below":"https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=310339",
    "20percent_up":"https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=310341",
    "20percent_down":"https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=310342",
    "4.5percent_up":"https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=334513",
    "4.5percent_down":"https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=338580",
    "20sma_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=421716",
    "50sma_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=423236",
    "20sma_below_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=423235",
    "50sma_below_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=423237",
    "20percent_up_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=423233",
    "20percent_down_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=423234",
    "4.5percent_up_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=421801",
    "4.5percent_down_nse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=423232",
    "20sma_crypto": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312530",
    "50sma_crypto": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312534",
    "20sma_crypto_below": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312529",
    "50sma_crypto_below": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312535",
    "20percent_crypto_up": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312536",
    "20percent_crypto_down": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312537",
    "9.5percent_crypto_up": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312532",
    "9.5percent_crypto_down": "https://www.marketinout.com/stock-screener/formula-crypto-screener.php?screen_id=312533",
    "20sma_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424624",
    "50sma_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424630",
    "20sma_below_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424623",
    "50sma_below_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424631",
    "20percent_up_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424627",
    "20percent_down_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424629",
    "4.5percent_up_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424626",
    "4.5percent_down_tse": "https://www.marketinout.com/stock-screener/formula_screener.php?screen_id=424625",
}